Register events with images
BrightCoders-Institute/reto-administrador-de-eventos-jdg pull request #17
Opened 2023-07-05 17:49 UTC by JoseLopezSolis

**The user will now be able to:**
- Update **images**
- Edit **images**

**What do I?**
- It's now a new migration to the database called **active_storate** to let the user add an image to the "events" model.

![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/77039326/a817d24a-c554-4334-91cd-6d66df9e2192)
![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/77039326/e6b10f1e-676b-4c4d-a1a9-42a8585cc563)
![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/77039326/804f6669-62ee-4099-bc7e-2a52908b35b9)

co-authored-by: hugocruz1234 cruzhugo1997@gmail.com
co-authored-by: JoseLopezSolis jlopez114@ucol.mx
co-authored-by: ballo1988 rounderjards@gmail.com
co-authored-by: sr-meh hector.m.rm@hotmail.com
co-authored-by: jcardenas0 jcardenas0@ucol.mx

2023-07-05 18:39 UTC, juperameza commented on app/controllers/home_controller.rb
>  class HomeController < ApplicationController
```suggestion
class HomeController < ApplicationController
       def index; end
```
You should have the index method

2023-07-05 18:41 UTC, juperameza requested changes
Just that one thing everything else looks good

2023-07-05 21:02 UTC, juperameza approved these changes
Lgtm

2023-07-05 21:44 UTC, claunicole approved these changes

2023-07-06 00:32 UTC, Ballo1988 commented
Done!

2023-07-06 00:33 UTC, merged