Verify and recover account
BrightCoders-Institute/reto-administrador-de-eventos-jdg pull request #25
Opened 2023-07-12 03:19 UTC by sr-meh

In this pull request 

- Add user email verification.
- The application sends an email to registered users to verify their mail. 
- The email confirms the registration process.
- The user can recover the password via email.
- The user can edit and remove images from events. 

![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/6729543/eba70e00-6c08-4c33-a865-8436a856003c)

![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/6729543/1eb0bae0-954b-4c05-9ed9-31d63e60785c)

![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/6729543/d2dbca29-c6a7-4546-830e-c5a84899932f)

![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/6729543/09bee2ed-23b4-4f1d-96c6-7d57b7f894ff)

![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/6729543/41b39115-10cc-47c2-a571-b39389f3b7ce)

![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/6729543/ffaefde3-2bbe-4fde-97a4-f56ef9cad84d)

![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/6729543/f5b4ff59-cde2-49ff-8590-1b452986f9b4)

![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/6729543/ebd31629-c752-4fcb-a169-7c7b22d558c9)

For more details check #21

2023-07-12 06:21 UTC, juperameza requested changes

2023-07-12 06:21 UTC, juperameza commented on config/environments/development.rb
> +    password: 'fqyqazczsufkdtaq',
This shouldn't be here 
Use [Rails credentials](https://blog.kiprosh.com/rails-encrypted-credentials/)

2023-07-13 15:21 UTC, juperameza approved these changes
Lgtm

2023-07-13 16:26 UTC, PudinDeveloper approved these changes

2023-07-13 23:46 UTC, merged