Automatic reminders
BrightCoders-Institute/reto-administrador-de-eventos-jdg pull request #27
Opened 2023-07-15 02:30 UTC by JoseLopezSolis

WHAT DID WE DO?
- Redis was installed for Sidekiq to work.
- Sidekiq is already now correctly configured.
- Added a field to the event called reminder date.
- The user will receive a reminder of the event on the date the user wants to be reminded.
- Now export CSV format is now correctly working with filter.

Examples:
Reminder for tomorrow:
![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/77039326/97f48f93-c844-41fd-9b1a-86f2a2f4651a)

Reminder for today:
![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/77039326/25dccc5b-0e38-4de9-aab7-5444f5773588)

Reminder email:
![image](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/77039326/b8dc7809-c70e-4e43-a826-07dd6f3daf74)

2023-07-17 23:11 UTC, juperameza requested changes

2023-07-17 23:11 UTC, juperameza commented on config/master.key
> +bc37a7980d2e8b7b8aa02017480d8893
Thus shouldn't be here at all

2023-07-17 23:23 UTC, Ballo1988 commented on config/master.key
> +bc37a7980d2e8b7b8aa02017480d8893
Seems like we didn't cofigured the gitignore properly. should be ok now

2023-07-18 01:02 UTC, juperameza approved these changes
Lgtm

2023-07-18 03:26 UTC, claunicole approved these changes

2023-07-18 23:49 UTC, merged