Testing test
BrightCoders-Institute/reto-administrador-de-eventos-jdg pull request #28
Opened 2023-07-19 01:55 UTC by sr-meh

- Implements tests for the event model.
- Update the README

2023-07-19 02:21 UTC, juperameza requested changes
Everything looks good just that nick pick of not leaving comments o your code. Also update the branch :+1: great job guys

2023-07-19 02:21 UTC, juperameza commented on config/schedule.rb
> +#end
If  you dont need this delete it 
```suggestion

```

2023-07-19 05:41 UTC, PudinDeveloper approved these changes
Same comments as @juperameza, everything else looks good. Well done.

2023-07-21 19:06 UTC, hugocruz1234 approved these changes

2023-07-21 19:07 UTC, Antonio3veces3 commented
Excelene!

2023-08-08 02:05 UTC, closed without merging