Home Page
BrightCoders-Institute/reto-administrador-de-eventos-jdg pull request #7
Opened 2023-06-27 01:49 UTC by Ballo1988

We've created the home page mapped its routes, and added the view and controller, it also now displays "Event Management System" in the top middle.
For more information see #1 

![HomePageIssue](https://github.com/BrightCoders-Institute/reto-administrador-de-eventos-jdg/assets/44328033/a6b64899-12ec-4518-8291-55bff28fe891)

2023-06-27 02:02 UTC, juperameza requested changes

2023-06-27 02:02 UTC, juperameza commented on app/views/events/index.html.erb
> +</div>
Add a new line at the end of this file.

2023-06-27 02:02 UTC, juperameza commented on config/routes.rb
>    # Defines the root path route ("/")
If you dont need this code delete it

2023-06-27 02:22 UTC, juperameza approved these changes

2023-06-27 04:41 UTC, JuanequeX requested changes

2023-06-27 04:41 UTC, JuanequeX commented on Gemfile
> +ruby '2.7.7'
Although `rails` [recommends](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#ruby-versions) the use of version 2.7.0 or a newer version of ruby, it will be better to use the newer version like `3.2.2` to have all the [newer power](https://www.rubyonmac.dev/how-to-upgrade-the-ruby-version-in-your-project#:~:text=need%20to%20upgrade.-,Why,-upgrade%20the%20Ruby) in this project.

2023-06-27 04:41 UTC, JuanequeX commented on Gemfile
> +gem 'rubycritic'
What is the reason to have two times the `rubycritic` and `reek` gems in your gemfile?  I think is better to remove and only put it on one time

2023-06-27 04:41 UTC, JuanequeX commented on Gemfile
> +gem 'reek'
```suggestion

```

2023-06-27 04:41 UTC, JuanequeX commented on app/views/events/index.html.erb
> +</div>
indented correctly this file at 2 spaces

2023-06-27 04:41 UTC, JuanequeX commented on app/views/layouts/application.html.erb
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorig
Now in rails 7 we have impormaps to set this kind of integration, please try it like this [tutorial](https://blog.eq8.eu/til/how-to-use-bootstrap-5-in-rails-7.html)

2023-06-27 04:41 UTC, JuanequeX commented on app/views/layouts/application.html.erb
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorig
[other option](https://eagerworks.com/blog/import-maps-in-rails-7#:~:text=Import%20Maps%20for%20libraries%20with%20css%C2%A0)

2023-06-28 02:15 UTC, JuanequeX approved these changes

2023-06-28 16:52 UTC, PudinDeveloper approved these changes

2023-06-28 23:42 UTC, merged